### ISSUE TITLE
Grammar issue. 

### ISSUE THREAD

**Issue by MrPhaze62** [Yun-Seo1/Open-World#1]
![image](https://github.com/Yun-Seo1/Open-World/assets/65294370/0182ba4f-5905-4a58-a9c9-ba7281585382)

oop. no one likes a capital 'F', that haunts u forever. ^_^

![image](https://github.com/Yun-Seo1/Open-World/assets/65294370/1491aa72-7f6e-4cad-abe2-2fa1bb402e7c)

capital eye is needed there, plox. heh. :3

![image](https://github.com/Yun-Seo1/Open-World/assets/65294370/8e58f53a-c014-4a51-bd0b-5908bb18afdb)

I feel like you're missing a word... perhaps is it... 'WORLD" :O

**Comment by MrPhaze62** [comment]
![image](https://github.com/Yun-Seo1/Open-World/assets/65294370/68e6c9c1-18a8-43c3-9d5f-5a178aef8a44)

the space... is no longer with us huh.

**Comment by Yun-Seo1** [comment]
Resolved
