### ISSUE TITLE
Locked out bug that crashes MAS.exe. (serious bug)

### ISSUE THREAD

**Issue by MrPhaze62** [Yun-Seo1/Open-World#2]
![image](https://github.com/Yun-Seo1/Open-World/assets/65294370/21f74f69-5ab0-4eea-b9d1-b453875bb23f)

i failed to get rickrolled by monika. it's a sad day. :(

upon clicking the computer in MC's room, that error throws up.

ignoring that twice causes MAS to lock itself out with just monika sprite. this is seriously needed to be fixed as it breaks the entire main MAS game amd eventually crashes the DDLC.exe, Dreamcached can confirm this too. I recommend you fix this before you release it to everyone.

![image](https://github.com/Yun-Seo1/Open-World/assets/65294370/d1175c73-204d-4d09-ac45-f5a2a2910d86)
after u ignore it, that shows up but should u click no, the whole game freezes up and THEN crashes at that point onward.

(also if ur a dummy who clicked yes for the reset persistant, u dun goof cause more errors throws up at that point into the main MAS menu. but u won't crash. best bug. <3 )

**Comment by Yun-Seo1** [comment]
Resolved
