### ISSUE TITLE
why

### ISSUE THREAD

**Issue by vip3xITA** [Yun-Seo1/Open-World#5]
![2023-08-12](https://github.com/Yun-Seo1/Open-World/assets/142094506/e635ceaa-354a-4567-826a-fa96ef8c7bd3)

**Comment by Yun-Seo1** [comment]
You downloaded the branch and not the release.
Go to the releases tab and download the OpenWorld.zip folder

**Comment by Yun-Seo1** [comment]
It's been a few days since you replied, I'm going to assume its fixed
