### ISSUE TITLE
error wwith submod

### ISSUE THREAD

**Issue by letofaggg** [Yun-Seo1/Open-World#8]
Qq all, I downloaded this submod, I wanted to have fun, but for some reason an error occurs((
it would be nice if you helped me figure it out, I'll attach a traceback
![Screenshot 2023-12-17 11-00-10](https://github.com/Yun-Seo1/Open-World/assets/154045657/92fd7572-3969-4787-a5d2-87b9ec550b74)

**Comment by Yun-Seo1** [comment]
You downloaded the source code instead of the actual release.
Go back to the main page of Open World. On the right, there should be a section called "Releases", Download the .zip file and readme.txt

**Comment by letofaggg** [comment]
> You downloaded the source code instead of the actual release. Go back to the main page of Open World. On the right, there should be a section called "Releases", Download the .zip file and readme.txt

Thanks, it helped

**Comment by Yun-Seo1** [comment]
Alright, i'll close this as solved
